name=GTNHExtLib
version=${version}
additionalVersions=
className=com.gtnewhorizons.gtnhextlib.core.rfb.GTNHExtLibRfbPlugin
transformerExclusions=com.gtnewhorizons.gtnhextlib;com.falsepattern.deploader;it.unimi.dsi.fastutil;org.joml;com.mojang.brigadier;xyz.wagyourtail.jvmdowngrader
versionConstraints=
loadBefore=
loadAfter=
loadRequires=
